USE [master]
GO

/****** Object:  Database [Karayollari]    Script Date: 6.06.2026 19:05:58 ******/
CREATE DATABASE [Karayollari]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Karayollari', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\Karayollari.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Karayollari_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\Karayollari_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Karayollari].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Karayollari] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Karayollari] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Karayollari] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Karayollari] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Karayollari] SET ARITHABORT OFF 
GO

ALTER DATABASE [Karayollari] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Karayollari] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Karayollari] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Karayollari] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Karayollari] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Karayollari] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Karayollari] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Karayollari] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Karayollari] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Karayollari] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Karayollari] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Karayollari] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Karayollari] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Karayollari] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Karayollari] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Karayollari] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Karayollari] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Karayollari] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Karayollari] SET  MULTI_USER 
GO

ALTER DATABASE [Karayollari] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Karayollari] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Karayollari] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Karayollari] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Karayollari] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Karayollari] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Karayollari] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [Karayollari] SET QUERY_STORE = ON
GO

ALTER DATABASE [Karayollari] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Karayollari] SET  READ_WRITE 
GO

